spring:
  data:
    mongodb:
      auto-index-creation: 'true'
  application:
    name: Cells
properties:
  setup: RANDOM
  ## Higher is less population -> ex: 1 in 15
  blockPopulation: '1'
  cellPopulation: '20'
  size:
    x: '1000'
    y: '1000'
    blockSize: '50'
  runmode: AUTO
  targetspeed: '1000'
