logging.level.slobben: DEBUG
spring:
  application:
    name: Cells

cells:
  setup: EMPTY
  threads: '20'

  random:
    blockPopulation: '1'
    cellPopulation: '2'

  chaos:
    enabled: 'true'
    max-hits: 20
    tics-to-spawn: 150

  pruning-per-generation: '100'

  size:
    x: '0'
    y: '0'
    blockSize: '500'

  runmode: AUTO
  targetspeed: '500'

  recording:
    max-recording-depth: 4
