spring:
  data:
    mongodb:
      auto-index-creation: 'true'
  application:
    name: Cells
properties:
  setup: RANDOM
  ## Higher is less population -> ex: 1 in 15
  blockPopulation: '1'
  cellPopulation: '6'
  size:
    x: '10000'
    y: '10000'
    blockSize: '50'
  runmode: AUTO
  targetspeed: '200'
