spring:
  application:
    name: Cells
properties:
  setup: CHAOS
  chaos:
    enabled: 'true'


  ## Higher is less population -> ex: 1 in 15
  blockPopulation: '1'
  cellPopulation: '6'
  size:
    x: '10000'
    y: '10000'
    blockSize: '500'
  runmode: AUTO
  targetspeed: '1000'
