logging.level.slobben: INFO
spring:
  application:
    name: Cells
  threads:
    virtual:
      enabled: true

cells:
  pruning-per-generation: '100'

  size:
    x: '0'
    y: '0'
    blockSize: '2000'

  runmode: AUTO
  targetspeed: '300'

  recording:
    max-recording-depth: 4
