spring:
  data:
    mongodb:
      auto-index-creation: 'true'
  application:
    name: Cells
properties:
  setup: RANDOM
  ## Higher is less population -> ex: 1 in 15
  blockPopulation: '4'
  cellPopulation: '5'
  size:
    x: '5000'
    y: '5000'
    blockSize: '100'
  runmode: AUTO
  targetspeed: '1000'
