# .github/workflows/deploy.yml
name: Build, Test and Deploy

on:
  push:
    branches:
      - master  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'      
          distribution: 'temurin'

      - name: Build JAR with Maven
        run: mvn clean install

      - name: Deploy JAR to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "/home/runner/work/ProjectCell/ProjectCell/target/CellService.jar"
          target: ${{ secrets.TARGET }}
          strip_components: 1

      - name: Restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop cellservice.service
            sudo systemctl start cellservice.service
            sudo systemctl is-active --quiet cellservice.service && echo "Service is running" || exit 1 
